apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cp4i-od-ibm-entitlement-key
spec:
  destination:
    namespace: cp4i-od
    server: https://kubernetes.default.svc
  project: 1-infrastructure
  source:
    path: payload/1-infrastructure/namespace/cp4i-od/ibm-entitlement-key
    repoURL: https://github.com/awasthan/gitops-test-cp4i-od-1
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  ignoreDifferences: []
